<?php
/**
 * @copyright Absolute Commerce Ltd.
 * @license https://abscom.co/terms
 */

/** @var Absolute\CacheBust\Block\Buttons $block */
?>

<div class="additional-cache-management">
    <h2>
        <span><?php echo __('Cache Busting') ?></span>
    </h2>
    
    <p>
        <button onclick="setLocation('<?php echo $block->getCacheBustAllUrl() ?>')" type="button">
            <?php echo __('Bust All URLs') ?>
        </button>
        <span><?php echo __('The same as clicking each of the below buttons individually.') ?></span>
    </p>
    
    <p>
        <button onclick="setLocation('<?php echo $block->getCacheBustStaticUrl() ?>')" type="button">
            <?php echo __('Bust Static URLs') ?>
        </button>
        <span><?php echo __('Invalidate cache of JavaScript, CSS and image files.') ?></span>
    </p>
    
    <p>
        <button onclick="setLocation('<?php echo $block->getCacheBustMediaUrl() ?>')" type="button">
            <?php echo __('Bust Media URLs') ?>
        </button>
        <span><?php echo __('Invalidate cache of product images, category images, etc.') ?></span>
    </p>
    
</div>
<br/>
